### ISSUE TITLE
Difference in error message when switching from proc-macro-error

### ISSUE THREAD

**Issue by zhassan-aws** [GnomedDev/proc-macro-error-2#1]
Thank you for creating this fork of `proc-macro-error`. We've switched to `proc-macro-error2` in https://github.com/model-checking/kani/pull/3493, but we observed a difference in the emitted error.

With `proc-macro-error`, the error was:
```
error: Cannot derive `Arbitrary` for `Wrapper` union
 --> union.rs:5:10
  |
5 | #[derive(kani::Arbitrary)]
  |          ^^^^^^^^^^^^^^^
  |
note: `#[derive(Arbitrary)]` cannot be used for unions such as `Wrapper`
 --> union.rs:6:7
  |
6 | union Wrapper {
  |       ^^^^^^^
  = note: this error originates in the derive macro `kani::Arbitrary` (in Nightly builds, run with -Z macro-backtrace for more info)
```
With `proc-macro-error2`, the error is:
```
error: Cannot derive `Arbitrary` for `Wrapper` union
       
         = note: `#[derive(Arbitrary)]` cannot be used for unions such as `Wrapper`
       
 --> union.rs:5:10
  |
5 | #[derive(kani::Arbitrary)]
  |          ^^^^^^^^^^^^^^^
  |
  = note: this error originates in the derive macro `kani::Arbitrary` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The two notable differences are:
1. The annotated item (`union Wrapper`) is no longer included in the error
2. The first `note` does not appear after the span.

Is the difference expected?

This is the code that emits the error:

https://github.com/model-checking/kani/blob/701f6fb8e26acf0c31f053cc1503a4139b277e29/library/kani_macros/src/derive.rs#L89

**Comment by GnomedDev** [comment]
The only thing I can think to have caused this is that it is no longer doing hacky nightly detection to use the unstable Diagnostic API. If you enable the `nightly` feature of this crate does it revert the error messages back?

**Comment by zhassan-aws** [comment]
> If you enable the nightly feature of this crate does it revert the error messages back?

Using the nightly feature does the trick!
```diff
$ diff -u without_nightly.log with_nightly.log 
--- without_nightly.log 2024-09-06 16:41:20.185980525 -0700
+++ with_nightly.log    2024-09-06 16:39:56.254197678 -0700
@@ -1,13 +1,15 @@
 Kani Rust Verifier 0.55.0 (standalone)
 error: Cannot derive `Arbitrary` for `Wrapper` union
-       
-         = note: `#[derive(Arbitrary)]` cannot be used for unions such as `Wrapper`
-       
  --> union.rs:5:10
   |
 5 | #[derive(kani::Arbitrary)]
   |          ^^^^^^^^^^^^^^^
   |
+note: `#[derive(Arbitrary)]` cannot be used for unions such as `Wrapper`
+ --> union.rs:6:7
+  |
+6 | union Wrapper {
+  |       ^^^^^^^
   = note: this error originates in the derive macro `kani::Arbitrary` (in Nightly builds, run with -Z macro-backtrace for more info)
 
 error: aborting due to 1 previous error
```
Thanks! I'll close this issue.
