### ISSUE TITLE
Error messages seemingly different between versions

### ISSUE THREAD

**Issue by pvichivanives** [GnomedDev/proc-macro-error-2#4]
In 1.79 the error message is different than in 1.81 (items in 1.79 and structs in 1.81). Not sure if its a bug or something inherent with new version of rust
![image](https://github.com/user-attachments/assets/808ea65c-dc91-4407-8485-a8ef61d243cc)

**Comment by GnomedDev** [comment]
This doesn't even look like an error fired by `proc-macro-error2`? This is just a normal rustc error in the tokens that your macro is expanding to from what I can see in the error, issue symptoms, and your codebase.

Please correct me if I'm wrong.

**Comment by pvichivanives** [comment]
Yep, my apologies, it seemed to be an issue that came up during a version change. I was making a pr switching from proc-macro-error to proc-macro-error2 so I mistakenly assumed it must have been related.
